language: python
python:
      - "3.6"
notifications:
    email:
        on_success: change # default: change
        on_failure: change # default: always

install:
        # We do this conditionally because it saves us some downloading if the
        # version is the same.
      - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
        else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        fi
      - bash miniconda.sh -b -p $HOME/miniconda
      - export PATH="$HOME/miniconda/bin:$PATH"
      - hash -r
      - conda config --set always_yes yes --set changeps1 no
      - conda update -q conda
        # Useful for debugging any issues with conda
      - conda info -a
      - conda create -n test python=3.6
      - source activate test
      - conda config --add channels anaconda
      - conda config --add channels conda-forge
      - conda config --add channels cta-observatory
      - conda install pytest-cov
      - conda install -c bryankim96 dl1_data_handler
script:
      - pytest --cov=dl1_data_handler
after_success:
      - coveralls
