package:
  name: dl1_data_handler
  version: "0.7.2"

source:
  git_rev: v0.7.2
  git_url: https://github.com/cta-observatory/dl1-data-handler.git

requirements:
  host:
    - python
    - setuptools

  run:
    - python

  test:
    imports:
      -dl1-data-handler

about:
  home: https://github.com/cta-observatory/dl1-data-handler
  license: MIT
  license_file: LICENSE
